/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Germany = new javax.swing.JPanel();
        GermanyNorth = new javax.swing.JPanel();
        GermanyCenter = new javax.swing.JPanel();
        GermanySouth = new javax.swing.JPanel();
        Yemen = new javax.swing.JPanel();
        YemenNorth1 = new javax.swing.JPanel();
        YemenCenter1 = new javax.swing.JPanel();
        YemenSouth = new javax.swing.JPanel();
        Italy = new javax.swing.JPanel();
        ItalyNorth2 = new javax.swing.JPanel();
        ItalyCenter2 = new javax.swing.JPanel();
        ItalySouth1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 535));
        getContentPane().setLayout(new java.awt.BorderLayout(0, 2));

        Germany.setPreferredSize(new java.awt.Dimension(484, 166));
        Germany.setLayout(new java.awt.BorderLayout());

        GermanyNorth.setBackground(new java.awt.Color(0, 0, 0));
        GermanyNorth.setPreferredSize(new java.awt.Dimension(166, 55));
        GermanyNorth.setLayout(new java.awt.BorderLayout());
        Germany.add(GermanyNorth, java.awt.BorderLayout.NORTH);
        GermanyNorth.getAccessibleContext().setAccessibleParent(GermanyNorth);

        GermanyCenter.setBackground(new java.awt.Color(255, 51, 51));
        GermanyCenter.setPreferredSize(new java.awt.Dimension(166, 55));
        Germany.add(GermanyCenter, java.awt.BorderLayout.CENTER);

        GermanySouth.setBackground(new java.awt.Color(255, 255, 0));
        GermanySouth.setPreferredSize(new java.awt.Dimension(10, 55));
        Germany.add(GermanySouth, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(Germany, java.awt.BorderLayout.NORTH);
        Germany.getAccessibleContext().setAccessibleParent(Germany);

        Yemen.setPreferredSize(new java.awt.Dimension(166, 166));
        Yemen.setLayout(new java.awt.BorderLayout());

        YemenNorth1.setBackground(new java.awt.Color(255, 51, 0));
        YemenNorth1.setPreferredSize(new java.awt.Dimension(166, 55));
        YemenNorth1.setLayout(new java.awt.BorderLayout());
        Yemen.add(YemenNorth1, java.awt.BorderLayout.NORTH);
        YemenNorth1.getAccessibleContext().setAccessibleName("");

        YemenCenter1.setBackground(new java.awt.Color(255, 255, 255));
        YemenCenter1.setPreferredSize(new java.awt.Dimension(166, 55));
        Yemen.add(YemenCenter1, java.awt.BorderLayout.CENTER);

        YemenSouth.setBackground(new java.awt.Color(0, 0, 0));
        YemenSouth.setPreferredSize(new java.awt.Dimension(10, 55));
        Yemen.add(YemenSouth, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(Yemen, java.awt.BorderLayout.CENTER);
        Yemen.getAccessibleContext().setAccessibleDescription("");
        Yemen.getAccessibleContext().setAccessibleParent(Yemen);

        Italy.setPreferredSize(new java.awt.Dimension(166, 166));
        Italy.setLayout(new java.awt.BorderLayout());

        ItalyNorth2.setBackground(new java.awt.Color(51, 204, 0));
        ItalyNorth2.setPreferredSize(new java.awt.Dimension(166, 55));
        ItalyNorth2.setLayout(new java.awt.BorderLayout());
        Italy.add(ItalyNorth2, java.awt.BorderLayout.WEST);

        ItalyCenter2.setBackground(new java.awt.Color(255, 255, 255));
        ItalyCenter2.setPreferredSize(new java.awt.Dimension(166, 55));
        Italy.add(ItalyCenter2, java.awt.BorderLayout.CENTER);

        ItalySouth1.setBackground(new java.awt.Color(255, 51, 51));
        ItalySouth1.setPreferredSize(new java.awt.Dimension(166, 55));
        Italy.add(ItalySouth1, java.awt.BorderLayout.EAST);

        getContentPane().add(Italy, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(516, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Germany;
    private javax.swing.JPanel GermanyCenter;
    private javax.swing.JPanel GermanyNorth;
    private javax.swing.JPanel GermanySouth;
    private javax.swing.JPanel Italy;
    private javax.swing.JPanel ItalyCenter2;
    private javax.swing.JPanel ItalyNorth2;
    private javax.swing.JPanel ItalySouth1;
    private javax.swing.JPanel Yemen;
    private javax.swing.JPanel YemenCenter1;
    private javax.swing.JPanel YemenNorth1;
    private javax.swing.JPanel YemenSouth;
    // End of variables declaration//GEN-END:variables
}
