/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package optionframe;

/**
 *
 * @author dell
 */
public class JoptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form JoptionFrame
     */
    public JoptionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nationalityG = new javax.swing.ButtonGroup();
        GenderG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "الهوايات:", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arabic Typesetting", 1, 36), new java.awt.Color(204, 0, 51))); // NOI18N

        jCheckBox5.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(0, 0, 255));
        jCheckBox5.setText("الرسم");
        jPanel1.add(jCheckBox5);

        jCheckBox4.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(0, 0, 255));
        jCheckBox4.setText("السباحه");
        jPanel1.add(jCheckBox4);

        jCheckBox3.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(0, 0, 255));
        jCheckBox3.setText("القراءه");
        jPanel1.add(jCheckBox3);

        jCheckBox6.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(0, 0, 255));
        jCheckBox6.setText("الكتابه");
        jPanel1.add(jCheckBox6);

        jCheckBox2.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(0, 0, 255));
        jCheckBox2.setSelected(true);
        jCheckBox2.setText("الجري");
        jPanel1.add(jCheckBox2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        nationalityG.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(0, 51, 255));
        jRadioButton4.setText("سعودي");
        jPanel2.add(jRadioButton4);

        nationalityG.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(0, 51, 255));
        jRadioButton5.setText("مصري");
        jPanel2.add(jRadioButton5);

        nationalityG.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(0, 51, 255));
        jRadioButton6.setText("عراقي");
        jPanel2.add(jRadioButton6);

        nationalityG.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(0, 51, 255));
        jRadioButton7.setText("سوري");
        jPanel2.add(jRadioButton7);

        nationalityG.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(0, 51, 255));
        jRadioButton8.setText("يمني");
        jPanel2.add(jRadioButton8);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createTitledBorder(null, "حدد جنسك !", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arabic Typesetting", 0, 24)))); // NOI18N

        GenderG.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(0, 51, 255));
        jRadioButton9.setText("انثى");
        jPanel3.add(jRadioButton9);

        GenderG.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(0, 51, 255));
        jRadioButton10.setText("ذكر");
        jPanel3.add(jRadioButton10);

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);
        jPanel3.getAccessibleContext().setAccessibleParent(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JoptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JoptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JoptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JoptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JoptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GenderG;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.ButtonGroup nationalityG;
    // End of variables declaration//GEN-END:variables
}
